name: ${NAMESPACE:-zilla-http-proxy-schema-inline}
services:
  zilla:
    image: ghcr.io/aklivity/zilla:${ZILLA_VERSION:-latest}
    pull_policy: always
    restart: unless-stopped
    ports:
      - 7114:7114
    healthcheck:
      interval: 5s
      timeout: 3s
      retries: 5
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/7114"]
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:29092
    volumes:
      - ./zilla.yaml:/etc/zilla/zilla.yaml
    command: start -v -e

networks:
  default:
    driver: bridge
